### ISSUE TITLE
PWM out of spec?

### ISSUE THREAD

**Issue by bergstar** [adafruit/Adafruit-Feather-328P-PCB#1]
Voltage on PWM signal on this board is below 0.5V - tested on D3. I was only able to trigger around 0.3V. On all other 328P boards I have (other then Adafruit) - both clone and original its close to 5V - I triggered around 4.4V

I can't find anywhere in datasheet that signal below 1.8V could be acceptable for ATmega328P

**Comment by ladyada** [comment]
hi for tech support please post in the forums!
